############################################################
#                         JParkour                         #
#                           v1.6                           #
############################################################

# You can find documentation or help about the plugin here: https://github.com/mitriyf/JParkour
# Or: https://vk.com/jdevs

# Don't remove the version setting.
version: 1.6

# Plugin settings.
settings:
  # Insert hex or minimessage.
  # minimessage - for Paper, 1.18+.
  # hex - It works starting from version 1.16.5, but if your server is lower than this version, do not change anything.
  # It will also work on lower versions, but without displaying the correct colors
  translate: hex
  # You can find out the language code by clicking on the link below and looking at the In-Game section.
  # https://minecraft.fandom.com/wiki/Language#Languages
  # Or you can find out your language code by running the command (don't forget to change the language on the client):
  # /jparkour admin locale - Get the client's language code.
  # You can configure locales in the plugin folder where the locales. The folder will be created when you enable locales
  # in the plugin configuration. You can create your own files.
  # Set true to enable locales for messages.
  locales: false
  # Game settings.
  games:
    # XIDX is the world's ID.
    # Worlds are deleted after the next launch.
    world: "jparkour-XIDX"
    # Enter the maximum number of worlds that the plugin can use.
    # If the worlds are full, the player will be put in a queue and wait for any available server.
    amount: 999
    # Is it possible to delete the map after the game ends?
    # Set it to false if you are concerned about errors in the game console.
    # When set to true, it may cause server crashes! The plugin automatically deletes worlds after launch.
    deleteWhenClosing: false
    # Specify in ticks the amount of delay for pressing the item marked restart. 1 second = 20 ticks.
    restartCooldown: 100
  # Notification of updates.
  updater:
    # Is it enabled?
    # Updates are checked when the plugin is enabled.
    enabled: true
    # Auto-update settings.
    settings:
      # Enable this to update only critical updates.
      required: true
      # Enable this feature to update the plugin with any new versions.
      release: false
  # Plugin support.
  supports:
    # Enable PlaceholderAPI support.
    placeholderAPI: false
    # Tops settings.
    tops:
      # Enable Tops support.
      # If you want to see the result of the tops through placeholders, the PlaceholderAPI feature must be enabled!
      enabled: true
      # How often will the tops be updated? (In seconds)
      updateInterval: 900
  # Stands.
  armor-stands:
    # Types:
    # Bomb - explodes, and you need to select an item and click the type so that it doesn't explode.
    # Use - doesn't explode.
    # Clicks:
    # RIGHT_CLICK - right click.
    # LEFT_CLICK - left click.
    bomb_gold:
      # Material block.
      block: YELLOW_STAINED_GLASS
      # For older versions.
      blockData: 4
      # The material block is inside.
      in_block: TNT
      # For older versions.
      in_blockData: 0
      # The type of stand.
      type: bomb
      # An item that can defeat a stand.
      # Only an object with this material can defeat this stand!
      # This is because versions 1.8 and above do not have CustomModelData.
      item: GOLDEN_SWORD
      # Which key should I press?
      click_type: RIGHT_CLICK
    bomb_diamond:
      block: BLUE_STAINED_GLASS
      blockData: 11
      in_block: TNT
      in_blockData: 0
      type: bomb
      item: DIAMOND_SWORD
      click_type: RIGHT_CLICK
    diamond_block:
      block: BLUE_STAINED_GLASS
      blockData: 11
      in_blockData: 0
      in_block: DIAMOND_BLOCK
      type: use
      item: DIAMOND_SWORD
      click_type: LEFT_CLICK
    gold_block:
      block: YELLOW_STAINED_GLASS
      blockData: 4
      in_block: GOLD_BLOCK
      in_blockData: 0
      type: use
      item: GOLDEN_SWORD
      click_type: LEFT_CLICK

# Set up the message.
# This will only work if you have selected the plugin configuration mode.
# If you have enabled locales, the messages below will be displayed by default if the language is not set.
messages:
  # Actions:
  # [actionbar] message - Send the actionbar with your message. For 1.11+
  # [message] message - Send a message to the player.
  # [broadcast] message - Send a message to all players.
  # [log] message - Send a message to the console.
  # [delay] ticks - Make a delay between actions. In ticks. (20 ticks = 1 second)
  # [player] message - Execute a message on behalf of the player. (or a command via /)
  # [teleport] world;x;y;z;yaw;pitch;delay - Teleport the player to the specified coordinates. The delay is measured in ticks.
  # [console] command - Run the command on behalf of the console.
  # [title] title;subtitle;fadeIn;stay;fadeOut - Send the title to the player. For 1.8+
  # [sound] sound;volume;pitch;delay - Perform a sound for the player. The delay is measured in ticks.
  # Search for sounds here: https://helpch.at/docs/$version$/org/bukkit/Sound.html
  # // Replace $version$ with the version of your server, for example: https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
  # [effect] type;duration;amplifier;delay - Give the effect to the player. The delay and duration is measured in ticks.
  # Find the types of effects here: https://helpch.at/docs/$version$/org/bukkit/potion/PotionEffectType.html
  # [explosion] power;setFire;breakBlocks;delay;addX;addY;addZ - Create an explosion. The delay is measured in ticks.
  # setFire, breakBlocks - set to false or true. addX, addY, addZ - double values that are added to the player's explosion location.
  # [bossbar] message;color;type;time;style;flag - Send a bossbar to a player with a message for a specific time. For 1.9+
  # Types:
  # stop - The bossbar will disappear after the time you specified in time (seconds)
  # time - Bossbar will animate the time that is running out.
  # Functions:
  # %time% - Seconds left.
  # You can find all the functions like color, style, and flag here: https://helpch.at/docs/$version$/org/bukkit/boss/BossBar.html
  #
  # Placeholders:
  # %jparkour_map% - Displays the name of the map.
  # %jparkour_id% - Displays the ID of the map.
  # %jparkour_status% - Displays the status of the map.
  # %jparkour_lefts% - Displays the number of clicks on the stand.
  # %jparkour_maxlefts% - Displays the maximum number of clicks on the stand.
  # %jparkour_rights% - Displays the number of clicks on the bomb.
  # %jparkour_maxrights% - Displays the maximum number of bomb clicks.
  # %jparkour_tops_SchematicName_Number_name% - Get the name of a player who is on a specific top.
  # %jparkour_tops_SchematicName_Number_top% - Get a player's place in the top.
  # %jparkour_tops_SchematicName_Number_accuracy% - Get the accuracy of a player who is on a specific top.
  # %jparkour_tops_SchematicName_Number_time% - Get the exact completion time of a player who is on a specific top.
  #
  # Change "SchematicName" to the schematics' ID, and "Number" to the number in the top that you require.
  # If you don't know the player's position in the top, you can get it by replacing "Number" with "name=PlayerName".
  # Enter the player's nickname in PlayerName. Examples: %jparkour_tops_nether_1_top%,
  # %jparkour_tops_nether_name=Mitriyf_top%, %jparkour_tops_nether_name=%player%_top%.
  #
  # Built-in placeholders:
  # %accuracy% - Display the player's execution accuracy.
  # %star_win% - Displays the stars that the player has earned.
  # %star_loss% - Displays the stars that the player has not earned.
  #
  # Info:
  # Messages sent to the console may not replace placeholders or perform certain actions above.
  # Built-in functions:
  # %player% - Get the player name.
  #
  # The command message.
  cmd:
    help:
      - "[message] &a[JParkour] Help &7(/jparkour help):"
      - ""
      - "[message] &a/jparkour status &f- Check the status of the plugin."
      - "[message] &a/jparkour join &f- Create or join any available room."
      - "[message] &a/jparkour join roomId &f- Attempt to connect to the room (if it is free)."
      - "[message] &a/jparkour exit &f- Exit the game/queue."
      - "[message] &a/jparkour admin &f- Get a Admin Help."
      - "[message] &a/jparkour reload &f- Reload the plugin configuration."
      - ""
    noperm:
      - "[message] &cYou do not have sufficient permissions!"
  game:
    room:
      notfound:
        - "[message] &cThis map does not exist."
      started:
        - "[message] &cThe game has already started."
      connect:
        - "[message] &aConnecting to the room &e%room%..."
      waiter:
        - "[message] &aYou have been placed in queue."
        - "[message] &fExit the queue: &c/jparkour exit"
      exit:
        - "[message] &cYou have left the queue."
      noExit:
        - "[message] &cYou are not in the game."
    status:
      wait: "&eWaiting"
      start: "&fPlaying"
      win: "&aVictory"
      left: "&fBlocks destroyed: &e%blocks%/&e%blocks_all%"
      right: "&fBombs repelled: &e%bombs%&f/&e%bombs_all%"
    placeholders:
      notClaimed: "Not claimed"
    actions:
      joined:
        - "[message] &aYou are connected to the game: &e%game%"
      started:
        - "[message] &eGame is started."
      ingame:
        - "[message] &cYou are in the game!"
      end:
        - "[message] &cThe game is over."
      restarted:
        - "[delay] 5"
        - "[message] &aThe game has been restarted."
      cooldownRestart:
        - "[message] &cYou can't reload the game that quickly."
      kicked:
        - "[message] &cThe game is over."
      damageHeart:
        - "[message] &c-1 &lâ™¥"
        - "[explosion] 1"
      win:
        - "[title] &aVictory;&e%star_win%&7%star_loss% &f- &e%accuracy%%"